version: '3'
services:
  pong-service:
    image: pong-service:1.0.0
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: "8081"
      SERVICE_CONFIG_PING_URL: http://ping-service:8080/api/v1/ping
  ping-service:
    image: ping-service:1.0.0
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
      SERVICE_CONFIG_PONG_URL: http://pong-service:8081/api/v1/pong
